In [1]:
import pandas as pd

pd_data = pd.read_csv('./movie_raw_data.csv', index_col=0)
pd_data

domain  target  \
0            00000.host       1   
1             00ysw.com       1   
2               0xo.net       1   
3            100161.com       1   
4            100fyy.net       1   
...                 ...     ...   
2247       zqb.cyol.com       0   
2248    zsb.cucn.edu.cn       0   
2249    zw.liuxue86.com       0   
2250  zy3.xidian.edu.cn       0   
2251  zyyjy.bucm.edu.cn       0   

                                                   text  
0                                  论坛列表 å
¶ä...  
1      首页 电影 连续剧 综艺 动漫 更多 > 动作片 喜剧片 爱情片 科幻片 恐怖片 剧情片 ...  
2      零零零 首页 無用 归档 搜索&标签 左邻右里 应急储备 到此一游 代码高亮 VP$10 ...  
3      首页 电影 连续剧 综艺 动漫 资讯 专题 留言 导航 取消 看过 登录 首页 电影 连续...  
4      100分影院 电视剧 电影 动漫 综艺 播出表 首页 电视剧 电影 动漫 综艺 播出表 观...  
...                                                 ...  
2247           中青在线 加入收藏 新闻回顾 检索 中青论坛 广告 首页 中国青年报 打印 关闭  
2248     首页 学校简介 校友风采 热点镜头 校园照片 国际交流  观看全景 招考信息 招生资讯...  
2249   作文 议论文 评论 最新更新 频道地图 九月最值得期待的院线电影 字典 九月最值得期待的院...  
2250   学校首页 English 首页 书院概况 书院简介 机构设置 团队介绍 书院动态 通知公告...  
2251   首页 组织机构 新闻动态 通知公告 政策文件 资源共享 联系我们     教育部中医学类专...  

[2252 rows x 3 columns]

In [2]:
import jieba

# 这段代码是把上面dataframe的text部分进行分词，然后转到列表里面去，方便进行tf-idf，结果可以看下面
all_text = []
for index in pd_data.index:
    item_text = []
    text = pd_data.iloc[index, 2]
    text = [i for i in text.split()]
    for i in text:
        for j in jieba.cut(i, cut_all=False):
            item_text.append(j)
    item_text = ' '.join(item_text)
    all_text.append(item_text)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\晚秋\AppData\Local\Temp\jieba.cache
Loading model cost 0.690 seconds.
Prefix dict has been built successfully.


In [3]:
all_text[:2]

['è ® º å \x9d \x9b å \x88 \x97 è ¡ ¨ å ¶ ä » \x96 æ µ \x8f è § \x88 å \x99 ¨ ç \x94 ¨ æ \x88 · ä º ¤ æ µ \x81 é \x97 ² è \x81 \x8a ç \x81 \x8c æ ° ´ è ® º å \x9d \x9b é \x82 £ ä ¸ ª ç ½ \x91 ç \x9b \x98 æ ³ ¨ å \x86 \x8c é \x80 \x81 1T ï ¼ \x9f å ³ é \x94 ® æ \x97 ¶ å \x88 » 119 æ ± \x82 å \x8a © é \x97 ® ç \xad \x94 ç ½ \x91 ç « \x99 å » º è ® ® yemo1408 å ½ ± è § \x86 å \x88 \x86 ä º « ç \x83 \xad é \x97 ¨ ç \x94 µ å ½ ± å \x8f \x8d è ´ ª é £ \x8e æ \x9a ´ 5 ( 2021 ) q134182528 ç \x83 \xad é \x97 ¨ å \x89 § é \x9b \x86 ç » ´ ä º ¬ ä ¼ å ¥ \x87 ï ¼ \x9a è \x8b ± ç \x81 µ ç ¥ \x9e æ ® ¿ q134182528 å ¯ » è § å ½ ± è § \x86 æ ± \x82 â \x80 \x9c ä ¸ \x8d ä º \x8c ç ¥ \x9e æ \x8e ¢ â \x80 \x9d ç \x94 µ å ½ ± ï ¼ \x8c ç £ \x81 å \x8a \x9b ä ¸ \x8b ä ¸ \x8d ä º \x86 ï ¼ \x8c æ \x9c \x89 æ ² ¡ æ \x9c \x89 ä ¿ \x9d å \xad \x98 ä º \x86 ç \x9a \x84 å \x84 å ¼ \x9f å \x93 ¦ æ \x89 \x91 å \x8b è \x84 ¸ è ½ ¯ ä » ¶ å \x88 \x86 ä º « ç \x94 µ è \x84 \x91 è ½ ¯ ä » ¶ å ¾ ® è ½ ¯ ç \x94 µ è \x84 \x9

In [4]:
MAX_FEATURES = 100

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(min_df=10, max_features=MAX_FEATURES)
X_tfidf = tfidf.fit_transform(all_text)
X_labels =X_tfidf.toarray() > 0
features = tfidf.get_feature_names_out()
for index in range(len(X_labels[0])):
    if X_labels[0][index] == True:
        print(features[index])

2021


In [6]:
tfidf.get_feature_names_out()

array(['10', '1080p', '2017', '2018', '2019', '2020', '2021', '2022',
       '4k', 'app', 'bd', 'com', 'hd', 'icp', 'the', '下载', '专题', '世界',
       '中国', '中字', '中心', '企业', '免费', '全部', '全集', '公告', '关于', '剧情', '剧情片',
       '动作', '动作片', '动态', '动漫', '动画', '喜剧', '喜剧片', '国产', '国语', '在线', '地图',
       '大全', '大陆', '学院', '少年', '工作', '影视', '影院', '恋爱', '恐怖', '恐怖片', '我们',
       '手机', '推荐', '故事', '教育', '新闻', '日本', '明星', '更新', '最新', '服务', '查看',
       '模板', '欧美', '游戏', '漫画', '热门', '爱情', '爱情片', '王牌', '生活', '电影', '电影网',
       '电视剧', '登录', '百度', '直播', '科幻片', '第一季', '第三季', '第二季', '第四季', '纪录片',
       '经典', '综艺', '网站', '美国', '联系', '英雄', '蓝光', '观看', '视频', '资源', '资讯',
       '软件', '迅雷', '韩国', '音乐', '首页', '高清'], dtype=object)

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer(max_features=MAX_FEATURES)
X_count = count.fit_transform(all_text)
print(X_count.toarray())
print(len(X_count.toarray()))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  2  0]
 [ 4 71  0 ...  0  1  0]
 ...
 [ 1  0  2 ...  0  0  0]
 [ 0  0  0 ...  0  3  0]
 [ 0  0  0 ...  0  1  0]]
2252


In [8]:
count.get_feature_names_out()

array(['10', '1080p', '2017', '2018', '2019', '2020', '2021', '2022',
       '4k', 'app', 'bd', 'com', 'hd', 'icp', 'the', '下载', '专题', '世界',
       '中国', '中字', '中心', '企业', '免费', '全部', '全集', '公告', '关于', '剧情', '剧情片',
       '动作', '动作片', '动态', '动漫', '动画', '喜剧', '喜剧片', '国产', '国语', '在线', '地图',
       '大全', '大陆', '学院', '少年', '工作', '影视', '影院', '恋爱', '恐怖', '恐怖片', '我们',
       '手机', '推荐', '故事', '教育', '新闻', '日本', '明星', '更新', '最新', '服务', '查看',
       '模板', '欧美', '游戏', '漫画', '热门', '爱情', '爱情片', '王牌', '生活', '电影', '电影网',
       '电视剧', '登录', '百度', '直播', '科幻片', '第一季', '第三季', '第二季', '第四季', '纪录片',
       '经典', '综艺', '网站', '美国', '联系', '英雄', '蓝光', '观看', '视频', '资源', '资讯',
       '软件', '迅雷', '韩国', '音乐', '首页', '高清'], dtype=object)

In [9]:
from sklearn.model_selection import train_test_split

X_train_tf, X_test_tf, y_train_tf, y_test_tf = train_test_split(X_tfidf.toarray(), pd_data.target.values, test_size=0.2)
X_train_ct, X_test_ct, y_train_ct, y_test_ct = train_test_split(X_count.toarray(), pd_data.target.values, test_size=0.2)

In [10]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC

def test_models(X_train, X_test, y_train, y_test):
    
#     if method == 'tfidf':
#         X_train = tfidf.transform(X_train)
#         X_test = tfidf.transform(X_test)
#     elif method == 'count':
#         X_train = count.transform(X_train)
#         X_test = count.transform(X_test)

    model1 = MultinomialNB()
    model1.fit(X_train, y_train)
    print('Naive_bayes: {:.2f} '.format(model1.score(X_test, y_test)))



    model2 = KNeighborsClassifier()
    model2.fit(X_train, y_train)
    print('kneighbors: {:.2f}'.format(model2.score(X_test, y_test)))


    model3 = LogisticRegression()
    model3.fit(X_train, y_train)
    print('LogisticRegression: {:.2f}'.format(model3.score(X_test, y_test)))


    model4 = RandomForestClassifier()
    model4.fit(X_train, y_train)
    print('RandomForest: {:.2f}'.format(model4.score(X_test, y_test)))


    model5 = DecisionTreeClassifier()
    model5.fit(X_train, y_train)
    print('DecisionTree: {:.2f}'.format(model5.score(X_test, y_test)))


    model6 = GradientBoostingClassifier()
    model6.fit(X_train, y_train)
    print('GradientBoost: {:.2f}'.format(model6.score(X_test, y_test)))


    model7 = SVC(kernel='rbf')
    model7.fit(X_train, y_train)
    print('SVM: {:.2f}'.format(model7.score(X_test, y_test)))
    
    return model1, model2, model3, model4, model5, model6, model7

In [11]:
test_models(X_train_ct, X_test_ct, y_train_ct, y_test_ct)

Naive_bayes: 0.89 
kneighbors: 0.86
LogisticRegression: 0.88


D:\latefallsapp\Anaconda\envs\d2l\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


RandomForest: 0.92
DecisionTree: 0.86
GradientBoost: 0.89
SVM: 0.86


(MultinomialNB(),
 KNeighborsClassifier(),
 LogisticRegression(),
 RandomForestClassifier(),
 DecisionTreeClassifier(),
 GradientBoostingClassifier(),
 SVC())

In [12]:
model1, _, model3, model4, _, model6, model7 = test_models(X_train_tf, X_test_tf, y_train_tf, y_test_tf)

Naive_bayes: 0.92 
kneighbors: 0.88
LogisticRegression: 0.92
RandomForest: 0.93
DecisionTree: 0.87
GradientBoost: 0.92
SVM: 0.92


In [13]:
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_val_score

models = []
# models.append(('naive_bayer', model1))
models.append(('LogisticRegression', model3))
models.append(('RandomForest', model4))
models.append(('GradientBoost', model6))
# models.append(('SVM', model7))

vote = VotingClassifier(estimators=models, voting='hard')
vote.fit(X_train_tf, y_train_tf)
vote.score(X_test_tf, y_test_tf)


# for model, model_name in zip([model1, model3, model4, model6, model7, vote], ['naive_bayer', 'LogisticRegression', 'RandomForest', 'GradientBoost','SVM', 'vote']):
#     score = cross_val_score(model, X_count.toarray(), pd_data.target.values, scoring='accuracy')
#     print('{} accuracy: {}'.format(model_name, score))

0.9290465631929047

In [14]:
import requests
import numpy as np
from lxml import etree

MAX_HREF_NUM = 50

def predict_url(model, url):
    response = requests.get(url, timeout=5)
    print(response.text)
    response.encoding = response.apparent_encoding
    html = etree.HTML(response.text)
    if html is None:
        print('Request Failed')
    html_data = html.xpath('//*[@href]/text()')  # 只选取“带有链接”的文本
    if len(html_data) >= MAX_HREF_NUM:  # 只选取前多少个带有链接的文本
        html_data = html_data[:MAX_HREF_NUM]
        
    one_item = ''
    for item in html_data:
        item = item.strip()
        one_item += ' '
        one_item += item
    
    item_text = []
    text = [i for i in one_item.split()]
    for i in text:
        for j in jieba.cut(i, cut_all=False):
            item_text.append(j)
    item_text = ' '.join(item_text)
    out= []
    out.append(item_text)
    out = np.array(out).reshape(-1,)
    out_tf = tfidf.transform(out).toarray()
    result = model.predict(out_tf)[0]
    return int(result)
    
def predict_file(model, path):
    with open(path, 'rb') as f:
        results = f.read()
        html = etree.HTML(results)
        if html is None:
            print('Request Failed')
            return 0
        html_data = html.xpath('//*[@href]/text()')
        if len(html_data) >= MAX_HREF_NUM:  # 只选取前多少个带有链接的文本
            html_data = html_data[:MAX_HREF_NUM]
            
    one_item = ''
        
    for item in html_data:
        item = item.strip()
        one_item += ' '
        one_item += item
    
    item_text = []
    text = [i for i in one_item.split()]
    for i in text:
        for j in jieba.cut(i, cut_all=False):
            item_text.append(j)
    item_text = ' '.join(item_text)
    out= []
    out.append(item_text)
    out = np.array(out).reshape(-1,)
    out_tf = tfidf.transform(out).toarray()
    result = model.predict(out_tf)
    return int(result)

In [15]:
import os

file_path_pms = '../splashHtmlCrawler/html/pms'
files_pms = os.listdir(file_path_pms)
num = 0
for file in files_pms:
    file_name = os.path.join(file_path_pms, file)
    result = predict_file(vote, file_name)
    if result == 0:
        num += 1
print(len(files_pms))
print(num)
print(num/len(files_pms))

file_path_pms = '../splashHtmlCrawler/html/notpms'
files_pms = os.listdir(file_path_pms)
num = 0
for file in files_pms:
    file_name = os.path.join(file_path_pms, file)
    result = predict_file(vote, file_name)
    if result == 1:
        num += 1
print(len(files_pms))
print(num)
print(num/len(files_pms))

957
178
0.18599791013584116
Request Failed
1469
53
0.03607896528250511
